"""
ashare_manual_pool_2d_momentum_top2_ptrade.py - GENERATED by QuantStudio Strategy Compiler.

strategy_id: ashare_manual_pool_2d_momentum_top2
profile: ptrade-default (ptrade_profile_version=1.0.0-default)
engine_semantics_version: 0.4.0-next-open-basket
renderer_version: 0.3.2-mvp
match_price_mode: next_open
rebalance_time: 9:31

Runtime compatibility guarantees:
- get_history may return pandas objects or NumPy structured arrays.
- unsupported/empty securities are skipped instead of crashing the strategy.
- daily multi-stock ranking never reads data[code] from BarDict.
- run_daily controls execution; handle_data is intentionally empty.
- Select minute-period backtesting on broker PTrade to honor 9:31.
- PTrade public APIs only; no local files, DuckDB, or batch history APIs.
"""

import numpy as np


def initialize(context):
    g.stock_list = ['600570.SS', '000001.SZ', '920001.BJ']
    g.lookback = 4
    g.max_positions = 2
    g.top_n = 2
    g.selected = []
    run_daily(context, rebalance, time='9:31')


def before_trading_start(context, data):
    scores = {}
    for code in g.stock_list:
        try:
            history = get_history(
                g.lookback, '1d',
                field=['close'], security_list=code,
                fq='dypre', include=False, is_dict=True
            )
            item = _lookup_history_item(history, code)
            closes = _finite_series(_extract_history_field(item, 'close'))
        except Exception as exc:
            log.info('Skipping %s: history request failed: %s' % (code, exc))
            continue


        required_return = 2 + 1
        if len(closes) < required_return or not np.all(np.isfinite(closes[-required_return:])):
            log.info('Skipping %s: fewer than %s valid daily closes' % (code, required_return))
            continue
        denominator = closes[-required_return]
        if denominator == 0:
            log.info('Skipping %s: zero return denominator' % code)
            continue
        score = (closes[-1] - denominator) / denominator
        if np.isfinite(score):
            scores[code] = float(score)

    candidates = list(scores.keys())
    if candidates:
        try:
            candidates = filter_stock_by_status(
                candidates, filter_type=['ST', 'HALT', 'DELISTING'], query_date=None
            )
        except Exception as exc:
            log.info('Status filter unavailable; retaining history-valid candidates: %s' % exc)
    candidates = [code for code in candidates if code in scores]
    sorted_codes = sorted(candidates, key=lambda code: scores[code], reverse=True)
    g.selected = sorted_codes[:g.top_n]
    log.info('Selected stocks for 9:31 rebalance: %s' % g.selected)


def rebalance(context):
    selected = list(g.selected)
    selected_bare = set(_bare_code(code) for code in selected)
    positions = context.portfolio.positions

    for actual_code in list(positions.keys()):
        if _bare_code(actual_code) not in selected_bare:
            try:
                order_target_value(actual_code, 0)
                log.info('Selling %s' % actual_code)
            except Exception as exc:
                log.info('Sell order failed for %s: %s' % (actual_code, exc))

    total_value = _portfolio_total_value(context)
    target_value = total_value / float(g.max_positions) if g.max_positions > 0 else 0.0
    for code in selected:
        try:
            order_target_value(code, target_value)
            log.info('Targeting %s value for %s' % (target_value, code))
        except Exception as exc:
            log.info('Target order failed for %s: %s' % (code, exc))


def handle_data(context, data):
    pass


def _portfolio_total_value(context):
    portfolio = context.portfolio
    for name in ('total_value', 'portfolio_value', 'total_asset'):
        value = getattr(portfolio, name, None)
        if value is not None:
            try:
                value = float(value)
                if np.isfinite(value) and value > 0:
                    return value
            except (TypeError, ValueError):
                pass
    market_value = sum(
        float(getattr(position, 'market_value', 0) or 0)
        for position in portfolio.positions.values()
    )
    return float(portfolio.cash) + market_value


def _lookup_history_item(history, code):
    if history is None:
        return None
    try:
        return history[code]
    except (KeyError, IndexError, TypeError, ValueError):
        pass
    target = _bare_code(code)
    try:
        keys = history.keys()
    except AttributeError:
        return None
    for key in keys:
        if _bare_code(key) == target:
            try:
                return history[key]
            except Exception:
                return None
    return None


def _extract_history_field(history_item, field):
    if history_item is None:
        return np.asarray([], dtype=object)
    try:
        values = history_item[field]
    except (KeyError, IndexError, TypeError, ValueError):
        return np.asarray([], dtype=object)
    if hasattr(values, 'values'):
        values = values.values
    return np.asarray(values, dtype=object)


def _bare_code(code):
    return str(code).strip().upper().split('.')[0]


def _finite_float(value):
    try:
        result = float(value)
    except (TypeError, ValueError):
        return None
    return result if np.isfinite(result) else None


def _finite_series(values):
    converted = []
    for value in np.asarray(values, dtype=object).reshape(-1):
        number = _finite_float(value)
        converted.append(number if number is not None else np.nan)
    return np.asarray(converted, dtype=float)


def _get_ma(close_array, num):
    if len(close_array) < num:
        return None
    value = close_array[-num:].mean()
    return round(value, 2) if np.isfinite(value) else None

