"""G3 strategy package builder: Spec → IR → dual Renderer → structured package.

Reuses the PR6a render.py (golden-protected dual renderer) and build_strategy_ir.
Produces a self-contained, deterministic strategy package directory:

    <strategy_id>__<package_version>/
      manifest.json              # version, entry points, digests, G2 linkage
      strategy_spec.json         # frozen input spec
      strategy_ir.json           # frozen IR
      <id>_quantstudio.py        # QuantStudio rendered strategy
      <id>_ptrade.py             # Strict-PTrade rendered strategy (no batch APIs)
      __init__.py                # package init (no side effects)
      README.md                  # generated docs

Boundaries:
- Deterministic: fixed render_timestamp sentinel; canonical JSON bytes; byte-identical
  rendered strategies across builds (render.py itself is deterministic given same IR).
- Path isolation: all outputs under the single package dir; nothing leaks to out_dir root.
- UTF-8 no BOM on all text files.
- Golden protection: render raises GoldenProtectionError on protected IDs.
- Does not modify G2 frozen artifacts or G1-I engine/API/test.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Optional

from ..build_strategy_ir import build_strategy_ir
from ..reference.source_digest import canonical_json_bytes
from ..render import (
    GoldenProtectionError,
    output_filename,
    render_ptrade,
    render_quantstudio,
)
from .manifest import build_manifest, write_manifest

PACKAGE_BUILDER_VERSION = "1.0.0"
DEFAULT_PACKAGE_VERSION = "0.1.0"

# Package init source: no side effects, no heavy imports. Documents the package.
_INIT_PY_TEMPLATE = '''"""Strategy package: {strategy_id} (v{version}).

Auto-generated by quantstudio.strategy_compiler.package.builder (G3).
This package contains the dual-rendered strategy (QuantStudio + Strict-PTrade),
the frozen Spec/IR, and a manifest. Importing this module has no side effects.
"""
'''

_README_TEMPLATE = '''# Strategy Package: {strategy_name}

- **strategy_id**: `{strategy_id}`
- **package_version**: `{version}`
- **target_platforms**: {platforms}
- **engine_semantics_version**: `{engine_semantics_version}`
- **builder_version**: `{builder_version}`

## Contents
- `manifest.json` — package manifest (entry points, artifact digests, G2 linkage)
- `strategy_spec.json` — frozen input Spec
- `strategy_ir.json` — frozen intermediate representation
- `{qs_file}` — QuantStudio rendered strategy
- `{pt_file}` — Strict-PTrade rendered strategy (no batch APIs)
- `__init__.py` — package init (no side effects)

## G2 reference closure
{g2_note}

## Boundaries
- Deterministic build (fixed render timestamp; canonical JSON).
- Generated by G3 package closure; no G4 release / CLI E2E / skill packaging.
- Does not modify G2 frozen artifacts or G1-I engine/API/test.
'''


def _package_dir_name(strategy_id: str, package_version: str) -> str:
    """Canonical package dir name: <strategy_id>__<version> (dots→underscore in version)."""
    safe_ver = package_version.replace(".", "_")
    return f"{strategy_id}__{safe_ver}"


def _write_canonical_json(obj: Any, path: Path) -> None:
    """Write JSON as canonical UTF-8 bytes (sorted keys, compact, no BOM)."""
    path.write_bytes(canonical_json_bytes(obj))


def _write_text_no_bom(text: str, path: Path) -> None:
    """Write text as UTF-8 without BOM."""
    path.write_text(text, encoding="utf-8", newline="\n")


def build_strategy_package(
    spec: Dict[str, Any],
    out_dir: str | Path,
    *,
    package_version: str = DEFAULT_PACKAGE_VERSION,
    g2_reference: Optional[Dict[str, Any]] = None,
) -> Path:
    """Build a deterministic strategy package from a strategy_spec.

    Args:
        spec: validated strategy_spec dict.
        out_dir: parent directory; a single package subdir is created within it.
        package_version: semver for the package (default 0.1.0).
        g2_reference: optional G2 frozen-closure path linkage.

    Returns:
        Path to the created package directory.

    Raises:
        GoldenProtectionError: if strategy_id is golden-protected.
    """
    strategy_id = spec["strategy_id"]
    strategy_name = spec.get("strategy_name", strategy_id)
    target_platforms = spec.get("target_platforms", ["quantstudio", "ptrade-default"])
    engine_semantics_version = spec.get("contract_versions", {}).get(
        "engine_semantics_version", "0.1.0-legacy")

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    pkg_dir = out_dir / _package_dir_name(strategy_id, package_version)
    pkg_dir.mkdir(parents=True, exist_ok=True)

    # Stage 1: build IR (Spec → IR)
    ir = build_strategy_ir(spec)

    # Stage 2: render dual-platform (IR → QuantStudio + Strict-PTrade)
    # render_quantstudio/render_ptrade raise GoldenProtectionError on protected IDs.
    qs_code = render_quantstudio(ir)
    pt_code = render_ptrade(ir)

    qs_file = output_filename(strategy_id, "quantstudio")
    pt_file = output_filename(strategy_id, "ptrade-default")

    # Stage 3: write all artifacts (deterministic encoding)
    _write_canonical_json(spec, pkg_dir / "strategy_spec.json")
    _write_canonical_json(ir.to_dict(), pkg_dir / "strategy_ir.json")
    _write_text_no_bom(qs_code, pkg_dir / qs_file)
    _write_text_no_bom(pt_code, pkg_dir / pt_file)
    _write_text_no_bom(
        _INIT_PY_TEMPLATE.format(strategy_id=strategy_id, version=package_version),
        pkg_dir / "__init__.py")

    # Stage 4: build + write manifest (after artifacts exist so digests compute)
    entry_points = [
        {"platform": "quantstudio", "filename": qs_file},
        {"platform": "ptrade-default", "filename": pt_file},
    ]
    artifact_filenames = [
        "strategy_spec.json", "strategy_ir.json", qs_file, pt_file,
        "manifest.json", "__init__.py",
    ]
    manifest = build_manifest(
        strategy_id=strategy_id,
        strategy_name=strategy_name,
        package_version=package_version,
        target_platforms=target_platforms,
        engine_semantics_version=engine_semantics_version,
        entry_points=entry_points,
        artifact_filenames=artifact_filenames,
        pkg_dir=pkg_dir,
        g2_reference=g2_reference,
        builder_version=PACKAGE_BUILDER_VERSION,
    )
    # write manifest, then re-read to recompute manifest's own digest entry (it's in artifact_digests)
    write_manifest(manifest, pkg_dir)
    # recompute manifest digest now that the file exists, and rewrite once for consistency
    manifest["artifact_digests"]["manifest.json"] = sha256_file_local(pkg_dir / "manifest.json")
    write_manifest(manifest, pkg_dir)

    # Stage 5: README (after manifest so it can reference final state)
    g2_note = "Not linked (no G2 reference closure provided)." if g2_reference is None else \
        f"Linked to G2 CP3 frozen closure (data_digest_status={manifest['g2_reference_closure']['data_digest_status']})."
    _write_text_no_bom(
        _README_TEMPLATE.format(
            strategy_name=strategy_name, strategy_id=strategy_id, version=package_version,
            platforms=", ".join(target_platforms),
            engine_semantics_version=engine_semantics_version,
            builder_version=PACKAGE_BUILDER_VERSION,
            qs_file=qs_file, pt_file=pt_file, g2_note=g2_note),
        pkg_dir / "README.md")

    return pkg_dir


def sha256_file_local(path: Path) -> str:
    """Local sha256 (deferred import to keep module-level clean)."""
    from ..reference.source_digest import sha256_file
    return sha256_file(path)
