"""G3 strategy package builder: Spec → IR → dual Renderer → structured package.

Reuses the PR6a render.py (golden-protected dual renderer) and build_strategy_ir.
Produces a self-contained, deterministic strategy package directory.

G3 audit-fix corrective changes:
- Build order: ALL non-manifest artifacts written FIRST, then digests computed,
  then manifest written ONCE (no self-reference, no rewrite).
- manifest.json excluded from artifact_digests (self-reference unsolvable);
  README.md included.
- Rebuild into an existing package dir clears stale files (rmtree + mkdir).
- G2 linkage: 4 frozen artifacts must exist (fail closed via G2ReferenceError),
  recorded by logical ID + sha256 (no absolute paths in manifest).

Boundaries:
- Deterministic, path-isolated, UTF-8 no BOM, cross-process stable.
- Golden protection: render raises GoldenProtectionError on protected IDs.
- Does not modify G2 frozen artifacts or G1-I engine/API/test.
"""
from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any, Dict, Optional

from ..build_strategy_ir import build_strategy_ir
from ..reference.source_digest import canonical_json_bytes, sha256_file
from ..render import (
    GoldenProtectionError,
    output_filename,
    render_ptrade,
    render_quantstudio,
)
from .manifest import build_manifest, write_manifest
from .manifest import G2ReferenceError  # re-export

PACKAGE_BUILDER_VERSION = "1.0.0"
DEFAULT_PACKAGE_VERSION = "0.1.0"

# Package init source: no side effects, no heavy imports. Documents the package.
_INIT_PY_TEMPLATE = '''"""Strategy package: {strategy_id} (v{version}).

Auto-generated by quantstudio.strategy_compiler.package.builder (G3).
This package contains the dual-rendered strategy (QuantStudio + Strict-PTrade),
the frozen Spec/IR, and a manifest. Importing this module has no side effects.
"""
'''

_README_TEMPLATE = '''# Strategy Package: {strategy_name}

- **strategy_id**: `{strategy_id}`
- **package_version**: `{version}`
- **target_platforms**: {platforms}
- **engine_semantics_version**: `{engine_semantics_version}`
- **builder_version**: `{builder_version}`

## Contents
- `manifest.json` — package manifest (entry points, artifact digests, G2 linkage)
- `strategy_spec.json` — frozen input Spec
- `strategy_ir.json` — frozen intermediate representation
- `{qs_file}` — QuantStudio rendered strategy
- `{pt_file}` — Strict-PTrade rendered strategy (no batch APIs)
- `__init__.py` — package init (no side effects)

## G2 reference closure
{g2_note}

## Boundaries
- Deterministic build (fixed render timestamp; canonical JSON).
- Generated by G3 package closure; no G4 release / CLI E2E / skill packaging.
- Does not modify G2 frozen artifacts or G1-I engine/API/test.
'''


def _package_dir_name(strategy_id: str, package_version: str) -> str:
    """Canonical package dir name: <strategy_id>__<version> (dots→underscore in version)."""
    safe_ver = package_version.replace(".", "_")
    return f"{strategy_id}__{safe_ver}"


def _write_canonical_json(obj: Any, path: Path) -> None:
    """Write JSON as canonical UTF-8 bytes (sorted keys, compact, no BOM)."""
    path.write_bytes(canonical_json_bytes(obj))


def _write_text_no_bom(text: str, path: Path) -> None:
    """Write text as UTF-8 without BOM, LF newlines."""
    path.write_text(text, encoding="utf-8", newline="\n")


def build_strategy_package(
    spec: Dict[str, Any],
    out_dir: str | Path,
    *,
    package_version: str = DEFAULT_PACKAGE_VERSION,
    g2_reference: Optional[Dict[str, Any]] = None,
) -> Path:
    """Build a deterministic strategy package from a strategy_spec.

    Args:
        spec: validated strategy_spec dict.
        out_dir: parent directory; a single package subdir is created within it.
        package_version: semver for the package (default 0.1.0).
        g2_reference: optional G2 frozen-closure path linkage (4 artifacts required
            if provided; fail-closed on missing).

    Returns:
        Path to the created package directory.

    Raises:
        GoldenProtectionError: if strategy_id is golden-protected.
        G2ReferenceError: if g2_reference provided but a frozen artifact is missing.
    """
    strategy_id = spec["strategy_id"]
    strategy_name = spec.get("strategy_name", strategy_id)
    target_platforms = spec.get("target_platforms", ["quantstudio", "ptrade-default"])
    engine_semantics_version = spec.get("contract_versions", {}).get(
        "engine_semantics_version", "0.1.0-legacy")

    # Stage 0 (fail-fast, before touching disk): build IR + render dual-platform.
    # GoldenProtectionError / G2ReferenceError raise HERE, before any package dir
    # is created, so failed builds leave no partial output on disk.
    ir = build_strategy_ir(spec)
    qs_code = render_quantstudio(ir)   # raises GoldenProtectionError on protected IDs
    pt_code = render_ptrade(ir)

    # G2 linkage validation also fails closed before disk writes (G2ReferenceError).
    if g2_reference is not None:
        g2_note = _g2_readme_note(g2_reference)  # may raise G2ReferenceError
    else:
        g2_note = "Not linked (no G2 reference closure provided)."

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    pkg_dir = out_dir / _package_dir_name(strategy_id, package_version)
    # Rebuild-safe: clear any stale package dir so old files don't survive.
    if pkg_dir.exists():
        shutil.rmtree(pkg_dir)
    pkg_dir.mkdir(parents=True, exist_ok=True)

    qs_file = output_filename(strategy_id, "quantstudio")
    pt_file = output_filename(strategy_id, "ptrade-default")

    # Stage 3: write ALL non-manifest artifacts first (deterministic encoding).
    _write_canonical_json(spec, pkg_dir / "strategy_spec.json")
    _write_canonical_json(ir.to_dict(), pkg_dir / "strategy_ir.json")
    _write_text_no_bom(qs_code, pkg_dir / qs_file)
    _write_text_no_bom(pt_code, pkg_dir / pt_file)
    _write_text_no_bom(
        _INIT_PY_TEMPLATE.format(strategy_id=strategy_id, version=package_version),
        pkg_dir / "__init__.py")

    # README written BEFORE manifest so its digest can be included.
    _write_text_no_bom(
        _README_TEMPLATE.format(
            strategy_name=strategy_name, strategy_id=strategy_id, version=package_version,
            platforms=", ".join(target_platforms),
            engine_semantics_version=engine_semantics_version,
            builder_version=PACKAGE_BUILDER_VERSION,
            qs_file=qs_file, pt_file=pt_file, g2_note=g2_note),
        pkg_dir / "README.md")

    # Stage 4: build manifest. artifact_filenames lists every NON-manifest file
    # (manifest never self-references). G2 linkage built inside (fail-closed).
    entry_points = [
        {"platform": "quantstudio", "filename": qs_file},
        {"platform": "ptrade-default", "filename": pt_file},
    ]
    artifact_filenames = [
        "strategy_spec.json", "strategy_ir.json", qs_file, pt_file,
        "__init__.py", "README.md",
    ]
    manifest = build_manifest(
        strategy_id=strategy_id,
        strategy_name=strategy_name,
        package_version=package_version,
        target_platforms=target_platforms,
        engine_semantics_version=engine_semantics_version,
        entry_points=entry_points,
        artifact_filenames=artifact_filenames,
        pkg_dir=pkg_dir,
        g2_reference=g2_reference,
        builder_version=PACKAGE_BUILDER_VERSION,
    )
    # Single manifest write — no self-reference, no rewrite. Stable.
    write_manifest(manifest, pkg_dir)

    # Stage 5: post-write per-file consistency verification (audit gate).
    _verify_artifact_digests(pkg_dir, manifest)

    return pkg_dir


def _g2_readme_note(g2_reference: Dict[str, Any]) -> str:
    """README note for G2 linkage (also validates existence, fail-closed)."""
    from .manifest import _build_g2_linkage  # reuse the same fail-closed logic
    linkage = _build_g2_linkage(g2_reference)
    return (f"Linked to G2 CP3 frozen closure (4 artifacts verified; "
            f"data_digest_status={linkage['data_digest_status']}).")


def _verify_artifact_digests(pkg_dir: Path, manifest: Dict[str, Any]) -> None:
    """Audit gate: every recorded artifact_digest equals the actual file's sha256.
    manifest.json is deliberately NOT in artifact_digests (no self-reference)."""
    for fname, recorded in manifest["artifact_digests"].items():
        p = pkg_dir / fname
        if not p.exists():
            raise AssertionError(f"manifest lists {fname} but file missing after build")
        actual = sha256_file(p)
        if actual != recorded:
            raise AssertionError(
                f"artifact digest mismatch for {fname}: manifest {recorded[:12]} != actual {actual[:12]}")
