"""
ashare_manual_pool_2d_momentum_top2_quantstudio.py - GENERATED by QuantStudio Strategy Compiler (PR6a).
Rendered from strategy_ir.json (build_id implicit). DO NOT hand-edit;
re-render from the Spec/IR instead.

strategy_id: ashare_manual_pool_2d_momentum_top2
profile: quantstudio (daily-bar-v1)
engine_semantics_version: 0.4.0-next-open-basket
renderer_version: 0.3.2-mvp
match_price_mode: next_open

Golden protection: if this strategy_id is golden-protected, render() would have
raised before reaching this template. This file is safe to overwrite only for
non-protected strategy_ids.
"""

import numpy as np


def initialize(context):
    # UniverseNode (kind=manual_list): multi-stock rotation strategy.
    g.stock_list = ['600570.SH', '000001.SZ', '920001.BJ']
    g.lookback = 4
    g.max_positions = 2
    g.top_n = 2


def before_trading_start(context, data):
    # DataLoadNode: batch history for all stocks (QuantStudio optimization).
    # get_history_batch returns CodeDict{code: DataFrame}; extract the close
    # column into a 1-D array per code for vectorized scoring.
    h = get_history_batch(g.stock_list, 4, '1d',
                          fields=['close'], fq='dypre', include=False)
    g.history = {_bare_code(code): np.asarray(df['close'].values, dtype=object)
                 for code, df in h.items()}
    # Selection-stage HardFilterNode: filter ST/HALT/DELISTING.
    g.stock_list = filter_stock_by_status(
        g.stock_list, filter_type=['ST', 'HALT', 'DELISTING'], query_date=None
    )


def handle_data(context, data):
    scores = {}
    for code in g.stock_list:
        hist = _finite_series(g.history.get(_bare_code(code), []))
        curr = _finite_float(data[code].close)
        if curr is None:
            continue
        series = np.concatenate((hist, [curr]))


        if len(series) < 2 + 1 or not np.all(np.isfinite(series[-2-1:])):
            continue
        denominator = series[-2-1]
        if not np.isfinite(denominator) or denominator == 0:
            continue
        score = (series[-1] - denominator) / denominator
        if np.isfinite(score):
            scores[code] = score


    sorted_codes = sorted(scores.keys(), key=lambda c: scores[c], reverse=True)
    selected = sorted_codes[:g.top_n]
    selected_bare = {_bare_code(code) for code in selected}

    positions = context.portfolio.positions
    for actual_code in list(positions.keys()):
        if _bare_code(actual_code) not in selected_bare:
            order_target_value(actual_code, 0)
            log.info('Selling %s' % actual_code)
    total_value = _portfolio_total_value(context)
    target_value = total_value / float(g.max_positions) if g.max_positions > 0 else 0.0
    for code in selected:
        order_target_value(code, target_value)
        log.info('Targeting %s value for %s' % (target_value, code))


def _portfolio_total_value(context):
    portfolio = context.portfolio
    for name in ('total_value', 'portfolio_value', 'total_asset'):
        value = getattr(portfolio, name, None)
        if value is not None:
            try:
                value = float(value)
                if np.isfinite(value) and value > 0:
                    return value
            except (TypeError, ValueError):
                pass
    market_value = sum(
        float(getattr(position, 'market_value', 0) or 0)
        for position in portfolio.positions.values()
    )
    return float(portfolio.cash) + market_value


def _bare_code(code):
    return str(code).strip().upper().split('.')[0]


def _finite_float(value):
    try:
        result = float(value)
    except (TypeError, ValueError):
        return None
    return result if np.isfinite(result) else None


def _finite_series(values):
    return np.asarray([
        converted if converted is not None else np.nan
        for converted in (_finite_float(value) for value in np.asarray(values, dtype=object).reshape(-1))
    ], dtype=float)


def _get_ma(close_array, num):
    if len(close_array) < num:
        return None
    value = close_array[-num:].mean()
    return round(value, 2) if np.isfinite(value) else None

