"""
etf_theme_rotation_quantstudio.py - GENERATED by QuantStudio Strategy Compiler (design_version 2.2).
Rendered from agent_strategy_design.json (strategy_id=etf_theme_rotation). DO NOT hand-edit;
re-render from the Spec/IR instead.

strategy_id: etf_theme_rotation
profile: quantstudio (daily-bar-v1)
engine_semantics_version: 0.4.0-next_open_basket
renderer_version: local-agent-2.2
match_price_mode: next_open
rebalance_mode: callback_basket

策略: ETF 热门主题五层轮动（动态池 + 次日开盘 basket 调仓）
  层1 过滤: get_etf_list_local(equity, active_only) + 近20日日均成交额>=1e6
  层2 动量: 5/10/20 日收益率横截面百分位 rank(0..1)，等权平均
  层3 均线: MA5>MA10>MA20>MA60 -> trend_score=1 否则 0
  层4 综合: 0.6*momentum + 0.4*trend，取前 top_n(5) 名
  层5 卖出: 持仓跌出当期前 top_n 名 或 MA5<MA10 -> 清仓
组合: 等权最多5只，初始资金10万，基准沪深300，总仓位0.95(留5%缓冲)
"""

# 性能优化豁免: 计算向量化（T5 逐位等价验证 PASS, 2026-08-12）
# 重渲染前需同步此优化到 IR/spec 或 skill 指令，否则 re-render 会覆盖丢失。

import numpy as np
import pandas as pd


# ===================== 策略参数（来自设计契约） =====================
TOP_N = 5                 # 持仓数量（R0-Q1=B）
MOMENTUM_W = 0.6          # 动量权重（R0-Q2=B）
TREND_W = 0.4             # 趋势权重（R0-Q2=B）
LIQ_MIN_AMOUNT = 1_000_000  # 近20日日均成交额下限（层1，元）
GROSS_EXPOSURE = 0.95     # 总仓位目标（留5%现金缓冲）
MA_S = 5
MA_M = 10
MA_L = 20
MA_XL = 60


def initialize(context):
    # 基准：沪深300（set_benchmark 内部 bare_code 化）
    set_benchmark('000300.SH')
    # ETF 交易口径：关闭印花税/过户费，仅佣金
    set_commission(type='ETF', commission_ratio=0.0003, min_commission=0.1)
    # 运行期状态（策略内部持仓缓存，引擎不自动提供）
    g.target_list = []
    g.universe_etf = []


def _pct_rank(x):
    """横截面百分位 rank (0..1)，NaN 给 0。"""
    s = pd.Series(x, dtype='float64')
    if s.notna().sum() == 0:
        return np.zeros(len(x))
    r = s.rank(pct=True)
    return r.fillna(0.0).values


def handle_data(context, data):
    # ---------- 层1: 动态池 + 权益类过滤 ----------
    today = context.current_dt.strftime('%Y-%m-%d')
    universe = get_etf_list_local(query_date=today, etf_type='equity', active_only=True)
    if not universe:
        return
    g.universe_etf = universe

    # 取历史（>= MA_XL + 缓冲，fq='pre' 前复权）
    count = MA_XL + 10
    hist = get_history_batch(universe, count, '1d',
                             fields=['close', 'amount'], fq='pre', include=False)

    # ---- 性能优化（2026-08-12）：逐只计算改为 numpy 2D 矩阵（右对齐 pad，T5 逐位等价）----
    # 第一步：过滤 valid codes（长度 + 流动性），收集 close/amount 数组
    valid_codes = []
    valid_closes = []
    valid_amounts = []
    for code in universe:
        df = hist.get(code)
        if df is None or len(df) < MA_XL:
            continue
        close = df['close'].astype('float64').values
        amount = df['amount'].astype('float64').values
        if np.nanmean(amount[-20:]) < LIQ_MIN_AMOUNT:
            continue
        valid_codes.append(code)
        valid_closes.append(close)
        valid_amounts.append(amount)

    if len(valid_codes) == 0:
        return

    # 第二步：右对齐 pad 构建 2D 矩阵（防 ragged array ValueError）
    max_len = max(len(c) for c in valid_closes)
    closes = np.full((len(valid_codes), max_len), np.nan)
    amounts = np.full((len(valid_codes), max_len), np.nan)
    for i in range(len(valid_codes)):
        v_c = valid_closes[i]
        v_a = valid_amounts[i]
        closes[i, -len(v_c):] = v_c      # 右对齐，左侧 NaN 填充
        amounts[i, -len(v_a):] = v_a

    # 第三步：向量化计算（nanmean 忽略左侧 NaN pad，等价于逐只取各自最后 N 根）
    ma5_arr = np.nanmean(closes[:, -MA_S:], axis=1)
    ma10_arr = np.nanmean(closes[:, -MA_M:], axis=1)
    ma20_arr = np.nanmean(closes[:, -MA_L:], axis=1)
    ma60_arr = np.nanmean(closes[:, -MA_XL:], axis=1)
    mom5 = closes[:, -1] / closes[:, -6] - 1
    mom10 = closes[:, -1] / closes[:, -11] - 1
    mom20 = closes[:, -1] / closes[:, -21] - 1
    liq_ok = np.nanmean(amounts[:, -20:], axis=1) >= LIQ_MIN_AMOUNT  # 已在第一步过滤，此处恒 True
    if len(valid_codes) == 0:
        return

    # ---------- 层2: 动量打分（横截面百分位 rank 等权平均） ----------
    r5 = _pct_rank(mom5)
    r10 = _pct_rank(mom10)
    r20 = _pct_rank(mom20)
    momentum = (r5 + r10 + r20) / 3.0

    # ---------- 层3: 均线多头打分 ----------
    ma5 = np.array(ma5_arr)
    ma10 = np.array(ma10_arr)
    ma20 = np.array(ma20_arr)
    ma60 = np.array(ma60_arr)
    bull = (ma5 > ma10) & (ma10 > ma20) & (ma20 > ma60)
    trend = np.where(bull, 1.0, 0.0)

    # ---------- 层4: 综合得分 -> 前 TOP_N 名 ----------
    composite = MOMENTUM_W * momentum + TREND_W * trend
    order = np.argsort(-composite)  # 降序
    top_idx = order[:min(TOP_N, len(valid_codes))]
    target_codes = [valid_codes[i] for i in top_idx]
    g.target_list = target_codes

    target_set = set(target_codes)
    # 计算每只目标 ETF 的 MA5/MA10 用于卖出条件2（均线走坏）
    ma_map = {valid_codes[i]: (ma5[i], ma10[i]) for i in range(len(valid_codes))}

    # ---------- 层5: 卖出 + 买入（basket 原子先卖后买） ----------
    total_value = context.portfolio.total_value
    per_weight = GROSS_EXPOSURE / TOP_N
    per_value = total_value * per_weight

    # 当前持仓（引擎侧）：positions 是 dict，key=代码(.SS/.SZ)，value=Position
    holding = dict(context.portfolio.positions)

    # 卖出：不在目标名单 或 均线走坏(MA5<MA10)
    for code in list(holding.keys()):
        if code not in target_set:
            order_target_value(code, 0)
            log.info('SELL(exited rank): %s' % code)
        else:
            m5, m10 = ma_map.get(code, (np.nan, np.nan))
            if not np.isnan(m5) and not np.isnan(m10) and m5 < m10:
                order_target_value(code, 0)
                log.info('SELL(MA broken): %s' % code)

    # 买入/调仓：目标名单内按等权设仓
    for code in target_codes:
        order_target_value(code, per_value)
        log.info('BUY/TARGET: %s value=%.0f' % (code, per_value))
