"""ETF Rotation Reference Oracle (PR6b-2A CP3).

INDEPENDENT HAND-WRITTEN reference implementation of the ETF rotation strategy.
NOT generated by ptrade-strategy-codegen or the Compiler Renderer.
NOT reverse-engineered from generated local/PTrade code.
This is the independent truth source for CP6 consistency comparison.

Implements all 9 frozen modules (plan §CP2):
  1. Static 13-ETF risk pool (manual_list, .SH/.SZ standard codes)
  2. close > MA20 > MA60 trend filter (persistent multi-head, not cross event)
  3. 25-day log-price regression (np.polyfit)
  4. Annualized return (exp(slope*250)-1)
  5. R² goodness-of-fit
  6. annualized_return × R² momentum score
  7. Volume surge filter (plan §6.3 frozen: volume[-1] vs mean(volume[-6:-1])×2.5)
     - unheld: exclude from candidates
     - held: exit at next_open
  8. Top3 equal-weight holding
  9. -8% stop loss (cost_basis vs T-1 raw close, fq=None) + 511880.SH defensive fallback

Frozen parameters (plan §2):
  - 13 ETF codes (standard .SH/.SZ)
  - 511880.SH defensive asset (independent of risk pool)
  - MA20/MA60, lookback=25, annual_trading_days=250
  - surge_multiplier=2.5, volume lookback=6
  - stop_loss_percent=0.08
  - benchmark 000300.SH (explicit set_benchmark)
  - ETF costs: commission 0.00005, min 0.5, no stamp tax / transfer fee
  - T-1 signal, next_open execution (match_price_mode set at engine level)
"""

import math
import numpy as np


# ── Frozen configuration (plan §2) ──────────────────────────────────────────

ETF_POOL = [
    "518880.SH", "513880.SH", "159770.SZ", "159819.SZ", "513100.SH",
    "159915.SZ", "515880.SH", "513120.SH", "159755.SZ", "159652.SZ",
    "510500.SH", "159870.SZ", "159995.SZ",
]
DEFENSIVE_ASSET = "511880.SH"
BENCHMARK = "000300.SH"

LOOKBACK_REGRESSION = 25
ANNUAL_TRADING_DAYS = 250
MA_FAST = 20
MA_SLOW = 60
MAX_POSITIONS = 3
SURGE_MULTIPLIER = 2.5
VOLUME_LOOKBACK = 6  # baseline window = volume[-6:-1] (5 bars, T-2 to T-6)
STOP_LOSS_PERCENT = 0.08


def initialize(context):
    g.etf_pool = list(ETF_POOL)
    g.defensive_asset = DEFENSIVE_ASSET
    set_universe(g.etf_pool + [g.defensive_asset])
    set_limit_mode("UNLIMITED")
    set_commission(commission_ratio=0.00005, min_commission=0.5, type="ETF")
    set_benchmark(BENCHMARK)
    g.max_positions = MAX_POSITIONS
    g.lookback = LOOKBACK_REGRESSION
    g.annual_td = ANNUAL_TRADING_DAYS
    g.ma_fast = MA_FAST
    g.ma_slow = MA_SLOW
    g.surge_mult = SURGE_MULTIPLIER
    g.stop_loss_pct = STOP_LOSS_PERCENT
    g.volume_lookback = VOLUME_LOOKBACK
    # Data load window: max(ma_slow*2, regression_lookback*2, volume_lookback+2)
    g.data_window = max(MA_SLOW * 2, LOOKBACK_REGRESSION * 2, VOLUME_LOOKBACK + 2)


def before_trading_start(context, data):
    """T-day pre-open: compute all signals from T-1 close (include=False)."""
    # Indicator data: front-adjusted (fq='pre') for trend/regression continuity.
    hist_pre = get_history(
        g.data_window, frequency="1d", field=["close", "volume"],
        security_list=g.etf_pool, fq="pre", include=False, is_dict=True,
    )
    # Stop-loss data: T-1 unadjusted close (fq=None) for cost comparison.
    raw_close = get_history(
        1, frequency="1d", field="close",
        security_list=g.etf_pool, fq=None, include=False, is_dict=True,
    )

    g.momentum_scores = {}
    g.trend_ok = {}
    g.volume_surge = {}
    g.t1_raw_close_bare = {}  # bare code → T-1 raw close (suffix-safe)
    g.all_negative = True

    for etf in g.etf_pool:
        # ── Boundary: insufficient history → skip ──
        if etf not in hist_pre or len(hist_pre[etf]["close"]) < g.lookback:
            continue
        close_pre = np.array(hist_pre[etf]["close"], dtype=float)
        vol_pre = np.array(hist_pre[etf]["volume"], dtype=float)

        # ── Module 2: trend filter close > MA20 > MA60 ──
        if len(close_pre) < g.ma_slow:
            continue  # insufficient for MA60
        ma20 = np.mean(close_pre[-g.ma_fast:])
        ma60 = np.mean(close_pre[-g.ma_slow:])
        t1_close_pre = close_pre[-1]
        trend_pass = t1_close_pre > ma20 > ma60
        g.trend_ok[etf] = trend_pass

        # ── Modules 3-6: regression × R² momentum score ──
        reg_data = close_pre[-g.lookback:]
        x = np.arange(len(reg_data))
        y = np.log(reg_data)
        # Boundary: zero variance → R²=0, score=0 (still participates in ranking/defense)
        if np.var(y, ddof=1) == 0:
            momentum_score = 0.0
            r_squared = 0.0
        else:
            slope, intercept = np.polyfit(x, y, 1)
            annualized_return = math.pow(math.exp(slope), g.annual_td) - 1
            residuals = y - (slope * x + intercept)
            ss_res = np.sum(residuals ** 2)
            ss_tot = (len(y) - 1) * np.var(y, ddof=1)
            r_squared = 1 - (ss_res / ss_tot) if ss_tot > 0 else 0.0
            momentum_score = annualized_return * r_squared
        # Boundary: NaN → exclude
        if np.isnan(momentum_score):
            continue
        g.momentum_scores[etf] = momentum_score
        if momentum_score >= 0:
            g.all_negative = False

        # ── Module 7: volume surge (frozen §6.3) ──
        # Frozen formula needs exactly volume_lookback bars: [-1] signal + [-lookback:-1] baseline.
        # E.g. lookback=6: volume[-1] (signal) + volume[-6:-1] (5 baseline bars) = 6 total.
        if len(vol_pre) >= g.volume_lookback:
            signal_vol = vol_pre[-1]
            baseline = np.mean(vol_pre[-g.volume_lookback:-1])  # [-6:-1]
            g.volume_surge[etf] = signal_vol > baseline * g.surge_mult
        else:
            g.volume_surge[etf] = False

        # ── T-1 raw close for stop-loss (store by bare code for suffix-safe matching) ──
        bare = etf.split(".")[0]
        if etf in raw_close and len(raw_close[etf]["close"]) > 0:
            g.t1_raw_close_bare[bare] = float(raw_close[etf]["close"][-1])

    # ── Module 9: stop-loss check on held positions ──
    # Suffix-safe: positions use .SS/.SZ but signals use .SH/.SZ.
    # Match by bare code (strip suffix) to bridge the two namespaces.
    g.stop_loss_exits = set()  # stores position keys (actual portfolio keys)
    for pos_key in list(context.portfolio.positions.keys()):
        bare = pos_key.split(".")[0]
        pos = get_position(pos_key)
        if pos.amount > 0 and pos.cost_basis > 0 and bare in g.t1_raw_close_bare:
            drawdown = (pos.cost_basis - g.t1_raw_close_bare[bare]) / pos.cost_basis
            if drawdown >= g.stop_loss_pct:
                g.stop_loss_exits.add(pos_key)  # store actual portfolio key for sell


def handle_data(context, data):
    """T-day execution (next_open fill at engine level).

    Exit priority (frozen, deduplicated per bare code — each position gets at
    most ONE exit reason per round):
      1. stop_loss       (cost_basis drawdown >= 8%)
      2. volume_surge    (held ETF with abnormal volume)
      3. defensive_clear (all-negative → sell risk, buy defensive)
      4. rotation_exit   (not in today's Top3 selected)

    NOTE on next_open basket rebalance limitation:
    In next_open mode, orders created on day T are filled at T+1 open. Sell proceeds
    are NOT available for same-day buys (engine checks cash at order-creation time,
    before the T+1 sell drain). This means a "sell A then buy B on the same T" will
    reject the buy if B's cost exceeds available cash after the sell pre-debit.
    """

    def _place_order(code, target_value, label):
        """Place order and log actual result (not just intent)."""
        result = order_target_value(code, target_value)
        if result is not None and hasattr(result, "status"):
            if result.status == "filled":
                log.info("%s 成交 %s" % (label, code))
            elif result.status == "pending":
                log.info("%s 待成交(T+1) %s" % (label, code))
            elif result.status in ("rejected", "noop"):
                reason = getattr(result, "reason", "unknown")
                log.info("%s 未成交 %s (reason=%s)" % (label, code, reason))
        else:
            log.info("%s 下单 %s" % (label, code))
        return result

    # Suffix-safe helpers: signals use canonical .SH/.SZ; positions use .SS/.SZ.
    defensive_bare = g.defensive_asset.split(".")[0]
    signal_bare_map = {e.split(".")[0]: e for e in g.etf_pool}
    held_bare = {pk.split(".")[0]: pk for pk in context.portfolio.positions.keys()}

    # ── Unified exit decision table (deduplicated by bare code) ──
    # exit_decisions[bare] = (position_key, reason)
    # Priority: stop_loss > volume_surge > defensive_clear > rotation_exit
    exit_decisions: dict[str, tuple[str, str]] = {}

    # Priority 1: stop-loss
    for pos_key in g.stop_loss_exits:
        if pos_key in context.portfolio.positions:
            bare = pos_key.split(".")[0]
            exit_decisions[bare] = (pos_key, "stop_loss")

    # Priority 2: volume surge (only if not already exit-decided)
    for pos_key in list(context.portfolio.positions.keys()):
        bare = pos_key.split(".")[0]
        if bare == defensive_bare or bare in exit_decisions:
            continue
        canonical = signal_bare_map.get(bare)
        if canonical and g.volume_surge.get(canonical, False):
            exit_decisions[bare] = (pos_key, "volume_surge")

    # Execute all exit decisions (one sell per bare code)
    for bare, (pos_key, reason) in exit_decisions.items():
        _place_order(pos_key, 0, "退出(%s)" % reason)

    # ── Module 9: defensive fallback ──
    if g.all_negative or not g.momentum_scores:
        # Sell remaining risk positions not already exited
        for pos_key in list(context.portfolio.positions.keys()):
            bare = pos_key.split(".")[0]
            if bare != defensive_bare and bare not in exit_decisions:
                _place_order(pos_key, 0, "防御清仓")
                exit_decisions[bare] = (pos_key, "defensive_clear")
        # Buy defensive if not held
        if defensive_bare not in held_bare:
            _place_order(g.defensive_asset, context.portfolio.total_value, "防御切换")
        return

    # ── Modules 1-8: candidate selection + Top3 ranking ──
    eligible = []
    for etf in g.momentum_scores:
        if g.trend_ok.get(etf, False) and not g.volume_surge.get(etf, False):
            eligible.append(etf)

    if not eligible:
        for pos_key in list(context.portfolio.positions.keys()):
            bare = pos_key.split(".")[0]
            if bare != defensive_bare and bare not in exit_decisions:
                _place_order(pos_key, 0, "无候选清仓")
                exit_decisions[bare] = (pos_key, "no_candidate_clear")
        if defensive_bare not in held_bare:
            _place_order(g.defensive_asset, context.portfolio.total_value, "防御切换")
        return

    ranked = sorted(eligible, key=lambda e: g.momentum_scores[e], reverse=True)
    selected_bare = set(e.split(".")[0] for e in ranked[:g.max_positions])

    # Rotation exits: positions not in selected and not already exited
    for pos_key in list(context.portfolio.positions.keys()):
        bare = pos_key.split(".")[0]
        if bare != defensive_bare and bare not in selected_bare and bare not in exit_decisions:
            _place_order(pos_key, 0, "轮动卖出")
            exit_decisions[bare] = (pos_key, "rotation_exit")

    # Buy selected with equal weight
    if defensive_bare in held_bare:
        _place_order(held_bare[defensive_bare], 0, "防御退出")
    per_stock_value = context.portfolio.total_value / g.max_positions
    for etf in ranked[:g.max_positions]:
        bare = etf.split(".")[0]
        if bare not in held_bare:
            _place_order(etf, per_stock_value, "买入(score=%.4f)" % g.momentum_scores.get(etf, 0))
